name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: wottop-production-deploy
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: [self-hosted, wottop-prod]
    steps:
      - name: Deploy
        run: /home/github-runner/wottop-deploy.sh
